### ISSUE TITLE
How to make it work in IE

### ISSUE THREAD

**Issue by AndrianD** [xdamman/selection-sharer#36]
First of all, thank you for this module you made! It's wonderful. I wonder how to make it work in IE 9 please.

Thank you very much for your help!

Cheers

**Comment by AlienSKP** [comment]
Microsoft stopped supporting Internet Explorer. 
IE9 is **officially**  outdated, so we do not have to deal with that shit anymore. 
(and this is so exciting to write that sentence!!!)

**Comment by AndrianD** [comment]
But many enterprise and above all, most of my clients still **deal** with that shit and won't upgrade for newer versions of IE for technical reasons, so your answer is not the solution.

**Comment by AlienSKP** [comment]
My answer IS the solution, @AndrianD . 
It is not the responsibility of community-driven script development to solve entreprises bad choices or laziness of 3% of worldwide audience who can't update to windows 10 for free (source: statcounter.com). 

You are dealing with a weird scenario : what are *technical reasons* that prevent companies to upgrade from a product that is not supported anymore (so no security) ?

**Comment by AlienSKP** [comment]
And to be honest and more clear with you, I have a solution for your **clients** or **entreprises** that use this script : pay me and I'll do whatever custom development your **clients** or **entreprise** need.

**Comment by AndrianD** [comment]
Unfortunately no, AlienSKP.
You want a scenario? ok.
Imagine you have an enterprise who deals with about 500 to 1000 employes. All of them work and share files with our old IE9 on a local remote. The entire system is connected to an old equipment that costs them dearly for updates. And I do not count the applications that are plugged and need updating too if you update the browser.
How many developers and long will **IT** cost them?
And they will never take that risk for a module right ?
Is it really important to do an update of an entire system for a social networking module? Does it would make sense for such a large company?
Have you calculated the risks that imply?

**Comment by AlienSKP** [comment]
LOL you're so funny man. 
Hey Adrian. In France we say something like << with "if" you can put Paris into a bottle >>

Your scenario is void : 
1 - If you are a 500 to 1000 employees company and you NEED that plugin to be compatible with IE9 (for whatever your shitty reasons are) so just HIRE A DEV TO DO IT instead of coming to github whining about your problems. 
2- I repeat : MICROSOFT STOPPED SUPPORTING OLD IE. IE IS NOT SAFE ANYMORE. So your company will HAVE to upgrade (And I think they can do it for free). And if they don't, for whatever stoopid reasons you can list, it is not GitHub's community responsibility to provide such company help for free.

I'm sure you can find someone to do custom web development for you.

Regards

**Comment by AndrianD** [comment]
Are you a talker or a developer?
The plugin has been updated and now working on IE9(thank you xdamman!). You see the developer has thought of others who are not necessarily coders like you and me.
It is necessary that you try to see a little further and understand that everyone is not always someone technique.

In total, you wrote three posts, but do not help solve the problem. Basically I think you're a great talker rather than developer.
LOL
